# -*- coding: utf-8 -*-
"""name.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KzkUWyPInD4iuqaftHVeJRPCQAJor10P
"""

name = input("Enter your name :")

